//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class level
    {
        public level()
        {
            this.loesung = new HashSet<loesung>();
        }
    
        public int level_id { get; set; }
        public Nullable<int> schwierigkeit { get; set; }
        public string regeln { get; set; }
    
        public virtual ICollection<loesung> loesung { get; set; }
    }
}
